### ISSUE TITLE
Responsiveness for Different Screen Sizes 

### ISSUE THREAD

**Issue by vincentcote87** [SibylLab/Program-Wars#122]
Look into how the page behaves with different screen sizes (tablets, laptops, large computer monitors, etc...). If needed change some of the layout.

**Comment by groadybones** [comment]
Tried some games on my phone and on different sized monitors and there's a couple things:
- as long as the games stay short, responsiveness stays the same across the board, games have a fixed score limit as of my next pull request so the length of games is a non-issue
- on particularly small screens such as a phone, the right side of the screen gets cut off and users have to scroll to see it (text is nearly impossible to read on a phone so user will likely be zoomed way in regardless)
- if the screen is small enough that things get cut off, no background appears behind the elements that were cut off when the user scrolls over to look at them (doesn't affect performance but it looks horrendous)

It might just be worth-while to cut access from mobile users if possible. Due to the size of the text on a mobile device, the user has to be zoomed in and will have to scroll regardless of whether or not we found a way to fit everything on one page.

**Comment by johnanvik** [comment]
@maimoona-bashir - seems like a good "testing" activity when you need something to work on.

**Comment by strinsberg** [comment]
I have "forced" the game to stay at a minimum width so that it won't distort if the browser is adjusted to small. However using media queries it is possible to get the screen to actually use totally different styling to adjust itself to different screen sizes.

Some info is here https://www.w3schools.com/css/css_rwd_mediaqueries.asp

A small example is show in the new code for #526 in src/components/landingPage/GameSetup.vue that moves the left edge of the component if the screen is smaller than a certain size.

I think this would be great, but with our game being much more than just text and some images it will be a sizeable project. Though perhaps quite worthwhile as things progress past initial research uses. Mobile is everywhere these days, but would require some creative thinking to get all of our new UI components onto a mobile screen in a way that was still playable.

**Comment by strinsberg** [comment]
I have setup the responsiveness to be relative to the default font height. This works really well for making the screen respond to different resolutions and look exactly the same, as long as the aspect ratio is the same. Really wide and flat ratios don't work, but in most cases a user must deliberately do this, though maybe some long skinny phones might make it happen.

Touch screen devices are a bit of a problem, more because of drag and drop. We could add buttons for all the things we currently allow drag and drop for, with a toggle for use on touch screens. The stacks you can drag to light up so adding a button at the same time would be easy. And one could also be added whenever the active card is method or instruction to play it on the play field. But this should be another pull request. In my opinion, if we want to allow phone play we should really come up with a second UI layout that kicks in on smaller screens. The current one makes things really small on a phone.

Screenshots of different screen sizes
![Screenshot from 2020-08-18 16-51-04](https://user-images.githubusercontent.com/45857986/90573580-fff5aa00-e173-11ea-9cdf-c4456e991aea.png)
![Screenshot from 2020-08-18 16-51-59](https://user-images.githubusercontent.com/45857986/90573630-1d2a7880-e174-11ea-8373-56218b328aee.png)
![Screenshot from 2020-08-18 17-00-41](https://user-images.githubusercontent.com/45857986/90573857-b78abc00-e174-11ea-9a25-f736034dd1c1.png)
![Screenshot from 2020-08-18 17-01-22](https://user-images.githubusercontent.com/45857986/90573862-b9ed1600-e174-11ea-91ae-071bc3a1d2ec.png)
![Screenshot from 2020-08-18 17-01-48](https://user-images.githubusercontent.com/45857986/90573866-bbb6d980-e174-11ea-84fd-c579d65a7aa6.png)
![Screenshot from 2020-08-18 17-01-51](https://user-images.githubusercontent.com/45857986/90573868-bce80680-e174-11ea-8cac-5f5513fafd87.png)
![Screenshot from 2020-08-18 17-02-03](https://user-images.githubusercontent.com/45857986/90573869-be193380-e174-11ea-8959-a485d09eeeca.png)
![Screenshot from 2020-08-18 17-02-10](https://user-images.githubusercontent.com/45857986/90573872-beb1ca00-e174-11ea-9a0d-3c190fe87595.png)
![Screenshot from 2020-08-18 17-02-16](https://user-images.githubusercontent.com/45857986/90573877-bfe2f700-e174-11ea-90f3-a40fd96866dd.png)
![Screenshot from 2020-08-18 17-02-23](https://user-images.githubusercontent.com/45857986/90573882-c1142400-e174-11ea-88fc-db293f713e0e.png)

Too flat
![Screenshot from 2020-08-18 17-04-48](https://user-images.githubusercontent.com/45857986/90573980-f7ea3a00-e174-11ea-8900-27d6afce0205.png)

I think we should consider this closed, and if we want to allow playing on phones create a new issue specific to that with new and relevant info to our program.

**Comment by strinsberg** [comment]
I am going to close this as I believe that it is taken care of for computer screens. I believe that if we want an issue for tablet and mobile screen sizes that it should be a new one to address the specific needs of mobile, most notably adding clickable elements to replace drag and drop when on mobile, as drag and drop will not work for touch screens.
