### ISSUE TITLE
Use a "close" button on card for discard

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/program-wars#429]
(From @mkshiblu in #417)

**Is your feature request related to a problem? Please describe.**
There is a separate discard button to discard the selected card. 

**Describe the solution you'd like**
If we provide a discard button as a close/ (x) symbol at the top right corner of each card we could easily close it.

**Comment by johnanvik** [comment]
This could be confusing and error-prone to the user.

**Comment by JaceRiehl** [comment]
I think this would be a good idea, however it would certainly be error prone and may not be user friendly for the demographic of the game.

**Comment by mkshiblu** [comment]
Using the close button (x) is going to be error prone as suggested since it might conflict with certain variable cards -

![image](https://user-images.githubusercontent.com/15908043/44484776-80aa6a00-a670-11e8-8165-c927c6aeb1ac.png)

**Some Options:**

1. Using the button panel (which would be useful to to re-use in mobile view #362 ), the delete/discard is enabled only when a card is selected - 

![image](https://user-images.githubusercontent.com/15908043/44485805-a8e79800-a673-11e8-8645-5ec8fbfe3ead.png)

2. Another approach could be when a card is long pressed (for example, hold for a second) the discard option would appear as an overlay over the card.

3. Lastly, for the current design, the discard button could only be enabled only when a card is selected.

**Comment by johnanvik** [comment]
As I've been playing more, I agree that we need to change this. 

What about a variation of #3 where the "close" button only appears on the corner of the card when the card is selected and only for that card? And we could use the "trash" symbol instead of "X" so as not to be confused on Rx.

**Comment by mkshiblu** [comment]
I agree with combining 1 & 3. However, I am not sure if the trash icon would look good on the corner and might take quite a bit of space. Maybe a subtract symbol could be used like below for the selected card?

![image](https://user-images.githubusercontent.com/15908043/44631295-b9f21b00-a98b-11e8-88ef-2831a248ffbb.png)

**Comment by groadybones** [comment]
Closing cause we don't even have this UI anymore

**Comment by johnanvik** [comment]
Let's keep this open for now, as this was about dealing with UI elements for discarding cards.

**Comment by groadybones** [comment]
This looks like it was more of an issue for the original UI, I don't really see what this accomplishes with the current UI

**Comment by johnanvik** [comment]
Let's move forward with this this summer. It will help to "declutter" the UI.

**Comment by strinsberg** [comment]
I have tried some things to add a discard button to the selected card.

![discard_button](https://user-images.githubusercontent.com/45857986/81120340-bd240500-8ee9-11ea-9dfe-1ef234279dfa.png)

I would have to play around with it a bit more to get the button to appear overlaid on the card instead of above it. Also, the color and image could easily be changed or adjusted.

**Comment by strinsberg** [comment]
I adjusted the button location so that it is over the card. I think it is a better place for it. With a little styling I think it could be easy to see and intuitive to use. Only problem is that where I am currently creating it in the code it causes extra space to be added above the list of cards. Not a lot of space, but the cards move a little up and down when selected or not.

The new position
![discard_button2](https://user-images.githubusercontent.com/45857986/81235713-d942a780-8fb8-11ea-895c-0371bb947fdd.png)

**Comment by johnanvik** [comment]
I'm guessing there is something that can be done with a z-dimension to get it to be overlayed.

Try checking out some of the examples at https://vuejsexamples.com/tag/overlay/. Maybe there is something that can help there.

**Comment by strinsberg** [comment]
Finished adding this feature. The button no longer affects the positions of the cards. In the end this was fixed with some simple CSS position tags. The button was replaced with an input element of image type so that the image can be more easily updated if desired. The current trash can icon works, but could probably be improved in the future.

![final_discard_button](https://user-images.githubusercontent.com/45857986/81346356-60eeeb80-9077-11ea-964c-e1a261d990d4.png)
