### ISSUE TITLE
Player Stacks modal

### ISSUE THREAD

**Issue by JaceRiehl** [SibylLab/program-wars#433]
The modal that is used to hack another player is currently the one that is used to view their stacks (by clicking on their name). The modals should be separate, as the way it is done is fairly hacky. I tried building one but I continually got an issue that added multiple backgrounds. This made it so you can't exit out of the modal without getting a black screen.

**Comment by johnanvik** [comment]
@JaceRiehl did some work with this. See PR #432.

**Comment by mkshiblu** [comment]
I think I can help with this. Give me some time to work on this issue.

**Comment by groadybones** [comment]
Just played a game where I was able to hack opponents stacks while they had an active firewall. Commenting here cause its likely an issue with the fact that everything is using the hack modal. When I have a chance I'll either split the modals or at least give them unique emits so their cases can be handled differently.

**Comment by groadybones** [comment]
Because of this, players are able to play a hack card in their hand without ever actually clicking on it. If a player draws a hack card, then clicks on an opponents name (not for hacking purposes), clickable hack buttons appear beside that players hackable stacks. If one of these buttons is clicked, then the game behaves as if the player had followed the proper hacking process and discards the hack card from their hand so it's not technically a problem, however it's something that should be addressed.

**Comment by johnanvik** [comment]
Needs verificataion.

**Comment by strinsberg** [comment]
This will be solved with #526 as we no longer do hacking this way.
