### ISSUE TITLE
Power Outage too disruptive?

### ISSUE THREAD

**Issue by JaceRiehl** [SibylLab/program-wars#498]
Submitter: tyler
best: generator/hacker
favorite: generator
hated: hacker/poweroutage

**Comment by johnanvik** [comment]
This is from one of the participants in a Destination Exploration session that ran. The participants were around 10 years old and spent the entire time playing a "2-player hot seat" with another of the participants. At the end of the session, I asked them to submit some feedback about what cards they most liked and disliked and suggestions for improvements.

**Comment by johnanvik** [comment]
Also see #497

**Comment by johnanvik** [comment]
I asked this person to elaborate on the "why", but it looks like he didn't.

From the informal comments, the players felt that "Power Outage" was too powerful ("overpowered" was the term they used) because it prevented you from playing cards and you may have to wait for several (an unknown amount) turns to get a "Battery Backup" or "Generator" card. I mentioned this to John Jr. and he agreed that he had noticed this also. So we may need to consider if or how we could limit the duration of the card. Perhaps turn it into something more like a "skip next turn"?

**Comment by groadybones** [comment]
I had also been thinking this for a while, I think making it a single turn
skip underpowers it a little too much and reduces the desirability of
battery backups to a degree but I had considered limiting the amount of
turns that its active for to either 3 or 5 turns. That way the player can
try to redraw a BB or generator in that time or if they have good cards in
their hand, wait it out. It still offers a bit of punishment either way but
doesn't pull the player out of the game for too long.

**Comment by johnanvik** [comment]
Five turns seems like it would feel too long for the player. Three turns seems a good limit to try for now. We can move to two if that feels too long for players.

**Comment by johnanvik** [comment]
@hastar07 will be addressing this as part of his thesis work.

**Comment by johnanvik** [comment]
See #536

**Comment by johnanvik** [comment]
Will be fixed by #536
