### ISSUE TITLE
Redo the opening screen

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/Program-Wars#560]
**Is your feature request related to a problem? Please describe.**
The opening screen is awkward to use. The center white space is down too far. This means I have to scroll down once I add a player a player or two as the "Start Game" button goes below the edge of the window.  

Also, the opening text is too large.

**Describe the solution you'd like**
 * Move the center item up.

**Additional context**
@groadybones did this up quickly last summer as I was using PW for an outreach. It needs some TLC.

**Comment by strinsberg** [comment]
Just a heads up. I am taking care of this with the update.

here are some screenshots of what it looks like. It now adjusts to the size of the screen so it doesn't look gross.

![Screenshot from 2020-05-29 11-32-08](https://user-images.githubusercontent.com/45857986/83288171-28d35800-a1a0-11ea-988d-e4d692054bb0.png)
![Screenshot from 2020-05-29 11-32-38](https://user-images.githubusercontent.com/45857986/83288191-2ec93900-a1a0-11ea-911a-0dc723a9700b.png)

**Comment by strinsberg** [comment]
This is done in #526, but I will leave the issue open until some play testing can be done. We may still want to introduce changes to the game setup, or @johnanvik suggested maybe finding a new background for the landing page.

**Comment by johnanvik** [comment]
@jsanvik - Look at new graphic assets for this.

**Comment by strinsberg** [comment]
We are thinking of adjusting the way that game modes are made to allow for 'levels' or 'leagues' or something to represent game modes with different elements and increased difficulty. This will mean eventually removing the current modes and replacing them with the levels as the functionality is added.

We will need to add a way of adding human and AI players to the game with a click of a button instead of by changing modes. We can still force 2 or 4 players, and later add some selection for teams if we do that.

This may tie in with #567 to make game length a choice or to spend some time deciding what length of game is best for each level of play.

We may also want to include a way for the players to pick avatars for themselves rather than getting automatically assign to one. Though this is a low priority for now.

**Comment by johnanvik** [comment]
> We are thinking of adjusting the way that game modes are made to allow for 'levels' or 'leagues' or something to represent game modes with different elements and increased difficulty. This will mean eventually removing the current modes and replacing them with the levels as the functionality is added.
> 
> We will need to add a way of adding human and AI players to the game with a click of a button instead of by changing modes. We can still force 2 or 4 players, and later add some selection for teams if we do that.
> 
> This may tie in with #567 to make game length a choice or to spend some time deciding what length of game is best for each level of play.
> 
> We may also want to include a way for the players to pick avatars for themselves rather than getting automatically assign to one. Though this is a low priority for now.

Some good ideas here. @strinsberg, create issues for them for tracking and close this.

**Comment by strinsberg** [comment]
some differing concerns moved to new issues #601 and #603
