### ISSUE TITLE
Return the game feature that ensures all players have taken the same number of turns

### ISSUE THREAD

**Issue by strinsberg** [SibylLab/Program-Wars#582]
**Is your feature request related to a problem? Please describe.**
Originally if one player finished the other player would get an opportunity to take a final turn. This was missed in the re-write.

**Describe the solution you'd like**
Either make all players get the same number of turns. Ie) if i am the first player to have gone and I reach the score limit every other player should get one last turn so that we all have taken the same number.

Or when one player reaches the limit all other players get to take one more turn. Ie) I am the last player to go and I hit the limit, but instead of the game ending all my opponents get to take one last turn. Some players will get more turns, but this is how some card games do things to keep it competitive at the end.

**Comment by johnanvik** [comment]
I'm not sure which way is the most "fair" to the players. Option #1 seems fair on the surface, but what if you go before the completing player? You may have thought you had more turns and planned accordingly. In that case, Option #2 seems the more "fair" choice.

**Comment by strinsberg** [comment]
Yeah I think both have their advantages. Most in person card games I have played I think use the second option. A lot of online type card games just end when someone wins. So I guess it really depends on what we feel is fair.

Perhaps we could only ensure that Human players get one last turn if an AI player finishes first, or multiple humans are playing.

**Comment by maimoona-bashir** [comment]
**There are two options:** 
1. All players will get same number of turns. 
**Problem**: Game will end soon (short game ).
players will focus on finishing the game with maximum numbers of repeat (nested loops) and variable card, to win the game.

2. All the players will be given chance to reach to limit score, winner should be judged the basis of bonuses i.e. discussed in 583, by comparing complete stack.
**Advantage:** players will not to play just to win the game, but will apply good programing practices rather than only using nested loops ( repeat cards)

**Comment by maimoona-bashir** [comment]
**There are two options:**

1.All players will get same number of turns.
**Problem:** Game will end soon (short game ).
players will focus on finishing the game with maximum numbers of repeat (nested loops) and variable card, to win the game.

2.All the players will be given chance to reach to limit score, winner should be judged the basis of bonuses i.e. discussed in 583, by comparing complete stack.

**Advantage:** players will not only play just to win the game, but will apply good programing practices rather than only using nested loops ( repeat cards)

**Comment by johnanvik** [comment]
+1 for Option 2.

**Comment by johnanvik** [comment]
@maimoona-bashir, please update this with the most recent information. I think we resolved this.

**Comment by maimoona-bashir** [comment]
The issue has not been resolved yet, although i started it but didn't manage to finish yet.

**Comment by strinsberg** [comment]
This is part of version 3. If player 1 get to limit all other players get to take their final turn. If last player get the limit the game just ends. This ensures all players get an equal number of turns.

**Comment by maimoona-bashir** [comment]
This issue has been resolved in version 3 of game.
