### ISSUE TITLE
Add an objective for using a Method

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/Program-Wars#616]
**Is your feature request related to a problem? Please describe.**
There used to be an objective for using group cards. This was removed with the removal of group cards.

**Describe the solution you'd like**
Add a side objective for using a method. A player can play (but not likely win?) the game without using a Method card, but we should still make it explicit that this is good practice by rewarding them for using it.

**Comment by johnanvik** [comment]
@maimoona-bashir, please look into this. It may already be done, it just needs some investigation.

**Comment by maimoona-bashir** [comment]
Noted.

**Comment by strinsberg** [comment]
Version 3 has a bonus of 10 points for getting your method to the max (9pts)

**Comment by maimoona-bashir** [comment]
There should be a method [Mx] like Repeat Rx.  This method can have instruction cards (unlike original method card) and perform normal function. This can declutter the player field and it can also be linked to public/Private method in terms of CS concepts.

**Comment by maimoona-bashir** [comment]
Method stack can only take 6 cards now, if the player doesn't play smartly and use small instructions rather than big (2,3), the method stack can't reach the max value (9 pts). There is no way the player can change the instruction cards after being played. 
if the player has 6 cards in stack but it doesn't make it 9 pts, he will not get bonus of 10 points.
**Motivation:** player will play bigger instructions to gain 9 pts , so that he can get bonus.
**Concept:**  write fewer lines of code if it can achieve the same result, it will be clear, readable and maintainable.
