### ISSUE TITLE
Move the triva and the rules into an HTML file

### ISSUE THREAD

**Issue by johnanvik** [SibylLab/program-wars#67]
Currently, the text for the trivia and rules is embedding the code. These should appear in the text/HTML files for easy of updating.

**Comment by johnanvik** [comment]
(From a Slack  conversation)
![image](https://user-images.githubusercontent.com/28762049/41786940-1f384874-7604-11e8-86d2-c67ee6f4c779.png)

**Comment by johnanvik** [comment]
There is also Browserfy (http://browserify.org/). It looks like there is an example of what we are trying to do in the "Browserify transform example using brfs" section of https://writingjavascript.org/posts/introduction-to-browserify

**Comment by johnanvik** [comment]
Both Browserify and Webpack seem to do the same thing, so it might be "6 of one, half a dozen of the other"

**Comment by JaceRiehl** [comment]
It looks like the Webpack html plug-in is for generating html files and Bowserify reads files using node.js's file-system which is what I was having problems with prior. I will keep looking.

**Comment by groadybones** [comment]
Not sure if I can't find any trivia links but the project currently uses HTML to display rules on the webpage so can this issue be closed? Seems like it was addressed.

**Comment by johnanvik** [comment]
@strinsberg - Something for you to look into.

**Comment by strinsberg** [comment]
I was already thinking of something like this. We could easily create data files for some of the text using JSON and load it where we need it to keep the actual text out of code that needs to change or update it. This fits with the modal we used for tutorial information with the icons I added in #501. In order to use the same modal component for different information the text has to be added to it when it is created. We could import a data file with text so that the passing of text is just a variable reference instead of a long string. Or we could split it up into multiple modal files so that they could be more easily styled in HTML and create those components, but this can get a bit messy.

The Rules Modal already keeps all of it's text in the HTML part of the components. I was in there the other day trying to clean up the formatting a bit. It is a really long file because of all the tabs it has. I do find that this starts to get a little difficult to navigate. We could just make sure any component that uses a lot of specific static text is a simple component with just HTML that can be used in other components. It is one of the things Vue is setup nicely for.

I will keep it in mind as I re-organize things for #526

**Comment by strinsberg** [comment]
For info popups for components the text is now inserted into the element in HTML like creating any HTML element. This allows the text to be styled however is needed easily. Since these popups are meant to have a small amount of information it does not affect the code too much and it moves it out of the JavaScript portion of the code.

For this and other textual elements, text that does not need to be styled can be saved as data in files. This is what I have done for tooltips for the effect icons under a player.

Anything that is going to be a large amount of text and needs to be styled with HTML can be created as it's own vue component and injected where it is needed. The component can be made with no JavaScript except an export statement. This is what I will eventually do for the Rules modal as the file it is in is really big and has become difficult to navigate, though the HTML is needed to make the rules easy to read.

**Comment by johnanvik** [comment]
@strinsberg, can this be closed?

**Comment by strinsberg** [comment]
I was planning on splitting up the Rules modal into separate components when I get started with documentation and other things. Mostly the Rules need to be re-written to reflect the new game once the majority of the changes have been merged.

I was using this issue, but it might be better to create a new one and close this one as they are not really as connected as they might seem.
